// ==========================================================================================
//   GameFrameX 组织及其衍生项目的版权、商标、专利及其他相关权利
//   GameFrameX organization and its derivative projects' copyrights, trademarks, patents, and related rights
//   均受中华人民共和国及相关国际法律法规保护。
//   are protected by the laws of the People's Republic of China and relevant international regulations.
//   使用本项目须严格遵守相应法律法规及开源许可证之规定。
//   Usage of this project must strictly comply with applicable laws, regulations, and open-source licenses.
//   本项目采用 Apache License 2.0 单协议分发，
//   This project is licensed solely under the Apache License 2.0,
//   完整许可证文本请参见源代码根目录下的 LICENSE 文件。
//   please refer to the LICENSE file in the root directory of the source code for the full license text.
//   禁止利用本项目实施任何危害国家安全、破坏社会秩序、
//   It is prohibited to use this project to engage in any activities that endanger national security, disrupt social order,
//   侵犯他人合法权益等法律法规所禁止的行为！
//   or infringe upon the legitimate rights and interests of others, as prohibited by laws and regulations!
//   因基于本项目二次开发所产生的一切法律纠纷与责任，
//   Any legal disputes and liabilities arising from secondary development based on this project
//   本项目组织与贡献者概不承担。
//   shall be borne solely by the developer; the project organization and contributors assume no responsibility.
//   GitHub 仓库：https://github.com/GameFrameX
//   GitHub Repository: https://github.com/GameFrameX
//   Gitee  仓库：https://gitee.com/GameFrameX
//   Gitee Repository:  https://gitee.com/GameFrameX
//   CNB  仓库：https://cnb.cool/GameFrameX
//   CNB Repository:  https://cnb.cool/GameFrameX
//   官方文档：https://gameframex.doc.alianblank.com/
//   Official Documentation: https://gameframex.doc.alianblank.com/
//  ==========================================================================================


using System.Net;
using System.Net.Sockets;
using MongoDB.Driver;

namespace GameFrameX.NetWork.RemoteMessaging.Discovery;

/// <summary>
/// Mongo 心跳写侧（C143d D11/D15 / D17 通道 1 与通道 4）。
/// </summary>
/// <remarks>
/// The Mongo heartbeat writer (C143d D11/D15; D17 channels 1 and 4).
/// Owns this process's document in the control database <c>server_heartbeat</c>
/// collection: an immediate upsert on start, then a full-document upsert every
/// heartbeat interval (5 s default). The upsert is always the complete latest
/// state, so after a Mongo outage every field recovers with the next successful
/// write — the failure cache only needs to remember that writes are pending,
/// which is the "cache latest state, batch-resend on recovery" mitigation in
/// practice (D15 risks). Graceful exit writes Stopped (D17 channel 4) instead of
/// waiting for the TTL: once on <see cref="StopAsync"/> and, as a best-effort
/// safety net, on <see cref="AppDomain.ProcessExit"/> — the full SIGTERM wiring
/// arrives with the compose signal handling of C143f.
/// </remarks>
public sealed class MongoEndpointRegistry : IDisposable
{
    /// <summary>
    /// 广播主机环境变量（D12：compose 模板生成；DNS 名一等缺省）。
    /// </summary>
    /// <remarks>
    /// The advertise host environment variable (D12, generated by the compose template; DNS names are the first-class default).
    /// </remarks>
    public const string AdvertiseHostEnvironmentVariable = "GameFrameX__AdvertiseHost";

    /// <summary>
    /// 广播端口环境变量（D12）。
    /// </summary>
    /// <remarks>
    /// The advertise port environment variable (D12).
    /// </remarks>
    public const string AdvertisePortEnvironmentVariable = "GameFrameX__AdvertisePort";

    /// <summary>
    /// 实例标识环境变量（D12；多实例同 Role 时用于稳定实例身份）。
    /// </summary>
    /// <remarks>
    /// The role instance id environment variable (D12; keeps the instance identity stable across fixed-instance deployments).
    /// </remarks>
    public const string RoleInstanceIdEnvironmentVariable = "GameFrameX__RoleInstanceId";

    /// <summary>
    /// 缺省心跳间隔（5s，D11）。
    /// </summary>
    /// <remarks>
    /// The default heartbeat interval (5 s, D11).
    /// </remarks>
    public static readonly TimeSpan DefaultHeartbeatInterval = TimeSpan.FromSeconds(5);

    /// <summary>
    /// server_heartbeat 集合名（D18 全名约定；稳定契约，运维与测试可直接引用）。
    /// </summary>
    /// <remarks>
    /// The server_heartbeat collection name (D18 no-abbreviation rule; a stable
    /// contract, safe to reference from operations tooling and tests).
    /// </remarks>
    public const string HeartbeatCollectionName = "server_heartbeat";

    /// <summary>
    /// TTL 索引保存时长（15s，D11：watcher 三周期阈值同值兜底）。
    /// </summary>
    /// <remarks>
    /// The TTL expire-after window (15 s, D11; matches the watcher three-period threshold).
    /// </remarks>
    private const long HeartbeatTimeToLiveSeconds = 15;

    /// <summary>
    /// 心跳集合。
    /// </summary>
    /// <remarks>
    /// The heartbeat collection.
    /// </remarks>
    private readonly IMongoCollection<ServerHeartbeatDocument> _collection;

    /// <summary>
    /// 本进程实例身份。
    /// </summary>
    /// <remarks>
    /// This process's instance identity (role, instance id, endpoint, incarnation).
    /// </remarks>
    private readonly InstanceDescriptor _selfDescriptor;

    /// <summary>
    /// 心跳间隔。
    /// </summary>
    /// <remarks>
    /// The heartbeat interval.
    /// </remarks>
    private readonly TimeSpan _heartbeatInterval;

    /// <summary>
    /// 心跳循环取消令牌源。
    /// </summary>
    /// <remarks>
    /// The cancellation token source of the heartbeat loop.
    /// </remarks>
    private readonly CancellationTokenSource _loopCancellation = new CancellationTokenSource();

    /// <summary>
    /// 心跳循环任务。
    /// </summary>
    /// <remarks>
    /// The heartbeat loop task.
    /// </remarks>
    private Task _loopTask;

    /// <summary>
    /// 是否已写终态 Stopped（幂等守卫）。
    /// </summary>
    /// <remarks>
    /// Whether the terminal Stopped state was already written (idempotent guard).
    /// </remarks>
    private int _stoppedWritten;

    /// <summary>
    /// 初始化 Mongo 心跳写侧。
    /// </summary>
    /// <remarks>
    /// Initializes the writer. Call <see cref="StartAsync"/> to begin heartbeating.
    /// </remarks>
    /// <param name="controlDatabase">控制库（gameframex_control）/ The control database</param>
    /// <param name="selfDescriptor">本进程实例身份 / This process's instance identity</param>
    /// <param name="heartbeatInterval">心跳间隔；缺省 5s / The heartbeat interval; defaults to 5 s</param>
    public MongoEndpointRegistry(IMongoDatabase controlDatabase, InstanceDescriptor selfDescriptor, TimeSpan? heartbeatInterval = null)
    {
        ArgumentNullException.ThrowIfNull(controlDatabase, nameof(controlDatabase));
        ArgumentNullException.ThrowIfNull(selfDescriptor, nameof(selfDescriptor));

        _collection = controlDatabase.GetCollection<ServerHeartbeatDocument>(HeartbeatCollectionName);
        _heartbeatInterval = heartbeatInterval ?? DefaultHeartbeatInterval;
        _selfDescriptor = selfDescriptor;
    }

    /// <summary>
    /// 从环境变量构建本进程实例身份（D12 广播引导）。
    /// </summary>
    /// <remarks>
    /// Builds this process's instance identity from the D12 bootstrap environment
    /// variables. The advertise host resolution order: the explicit
    /// <see cref="AdvertiseHostEnvironmentVariable"/> first (a DNS name is the
    /// first-class default), then egress-address detection (IPv4 preferred, IPv6
    /// tried next; a detection failure logs a warning and falls back to the machine
    /// name, per the D15 risks mitigation). Returns null when the advertise port is
    /// not configured — callers treat that as "no cross-process identity" and skip
    /// the write side (single-process local development).
    /// </remarks>
    /// <param name="roleName">承载的 Role 名 / The hosted role name</param>
    /// <returns>实例身份；未配置广播端口时为 null / The identity, or null when the advertise port is not configured</returns>
    public static InstanceDescriptor CreateSelfDescriptorFromEnvironment(string roleName)
    {
        var advertisePortText = Environment.GetEnvironmentVariable(AdvertisePortEnvironmentVariable);
        if (string.IsNullOrWhiteSpace(advertisePortText) || !int.TryParse(advertisePortText, out var advertisePort) || advertisePort < 1 || advertisePort > 65535)
        {
            return null;
        }

        var advertiseHostText = Environment.GetEnvironmentVariable(AdvertiseHostEnvironmentVariable);
        string advertiseHost;
        EndpointAddressKind addressKind;
        if (!string.IsNullOrWhiteSpace(advertiseHostText))
        {
            advertiseHost = advertiseHostText.Trim();
            addressKind = EndpointParser.Parse($"tcp://{advertiseHost}:{advertisePort}").AddressKind;
        }
        else
        {
            (advertiseHost, addressKind) = DetectEgressAddress();
        }

        var instanceId = Environment.GetEnvironmentVariable(RoleInstanceIdEnvironmentVariable);
        if (string.IsNullOrWhiteSpace(instanceId))
        {
            instanceId = $"{roleName}-{DateTimeOffset.UtcNow.ToUnixTimeMilliseconds():x}-{Guid.NewGuid().ToString("N").Substring(0, 8)}";
        }

        var incarnation = DateTimeOffset.UtcNow.UtcTicks;
        return new InstanceDescriptor(roleName, instanceId.Trim(), $"tcp://{advertiseHost}:{advertisePort}", InstanceStatus.Booting, 0, addressKind, incarnation, DateTime.UtcNow);
    }

    /// <summary>
    /// 启动心跳写侧：建 TTL 索引 + 立即 upsert Active + 起后台心跳循环。
    /// </summary>
    /// <remarks>
    /// Starts the writer: creates the TTL index (idempotent), upserts the Active
    /// document immediately so the watcher can discover this process within one
    /// poll round, then runs the background heartbeat loop. Also subscribes to
    /// <see cref="AppDomain.ProcessExit"/> as the best-effort Stopped safety net.
    /// </remarks>
    /// <param name="cancellationToken">取消令牌 / The cancellation token</param>
    /// <returns>异步任务 / Async task</returns>
    public async Task StartAsync(CancellationToken cancellationToken = default)
    {
        var indexKeys = Builders<ServerHeartbeatDocument>.IndexKeys.Ascending(document => document.LastHeartbeat);
        var indexOptions = new CreateIndexOptions { ExpireAfter = TimeSpan.FromSeconds(HeartbeatTimeToLiveSeconds), Name = "lastHeartbeat_ttl_15s" };
        await _collection.Indexes.CreateOneAsync(new CreateIndexModel<ServerHeartbeatDocument>(indexKeys, indexOptions), cancellationToken: cancellationToken);
        await UpsertHeartbeatAsync(InstanceStatus.Active, CancellationToken.None);
        AppDomain.CurrentDomain.ProcessExit += OnProcessExit;
        _loopTask = Task.Run(() => HeartbeatLoopAsync(_loopCancellation.Token));
    }

    /// <summary>
    /// 停止心跳写侧并写终态 Stopped（D17 通道 4 优雅退出）。
    /// </summary>
    /// <remarks>
    /// Stops the loop and writes the terminal Stopped state so watchers drop this
    /// instance immediately instead of waiting for the TTL. Idempotent.
    /// </remarks>
    /// <returns>异步任务 / Async task</returns>
    public async Task StopAsync()
    {
        _loopCancellation.Cancel();
        if (_loopTask != null)
        {
            try
            {
                await _loopTask;
            }
            catch (OperationCanceledException)
            {
            }
        }

        await WriteStoppedAsync();
        AppDomain.CurrentDomain.ProcessExit -= OnProcessExit;
    }

    /// <summary>
    /// 释放资源（未写终态时尽力同步写 Stopped）。
    /// </summary>
    /// <remarks>
    /// Disposes and, when Stopped was not written yet, writes it synchronously as a best effort.
    /// </remarks>
    public void Dispose()
    {
        try
        {
            _loopCancellation.Cancel();
            WriteStoppedAsync().GetAwaiter().GetResult();
        }
        catch (Exception)
        {
            // 尽力而为：进程退出路径上 Mongo 不可达时无法补写终态，交给 TTL 兜底清除。
        }
        finally
        {
            _loopCancellation.Dispose();
        }
    }

    /// <summary>
    /// 心跳循环：固定间隔全量 upsert。
    /// </summary>
    /// <remarks>
    /// The heartbeat loop: a full-document upsert every interval. Mongo-outage
    /// periods leave the document stale (the watcher marks the instance Offline
    /// after the three-period threshold — the designed D15 risk behavior); recovery
    /// is simply the next successful full upsert, which carries the complete
    /// latest state, so no queued per-field replay is needed.
    /// </remarks>
    /// <param name="cancellationToken">取消令牌 / The cancellation token</param>
    /// <returns>异步任务 / Async task</returns>
    private async Task HeartbeatLoopAsync(CancellationToken cancellationToken)
    {
        while (!cancellationToken.IsCancellationRequested)
        {
            try
            {
                await Task.Delay(_heartbeatInterval, cancellationToken);
                await UpsertHeartbeatAsync(InstanceStatus.Active, CancellationToken.None);
            }
            catch (OperationCanceledException)
            {
                break;
            }
            catch (Exception exception)
            {
                LogHelper.Error(exception, "[MongoEndpointRegistry] heartbeat upsert failed for instance {instanceId}; will retry next interval", _selfDescriptor.InstanceId);
            }
        }
    }

    /// <summary>
    /// 进程退出钩子：尽力同步写 Stopped。
    /// </summary>
    /// <remarks>
    /// The ProcessExit hook: writes Stopped synchronously with a short timeout.
    /// </remarks>
    /// <param name="sender">事件源 / The event source</param>
    /// <param name="eventArguments">事件参数 / The event arguments</param>
    private void OnProcessExit(object sender, EventArgs eventArguments)
    {
        try
        {
            WriteStoppedAsync().GetAwaiter().GetResult();
        }
        catch (Exception)
        {
            // 进程退出路径上 Mongo 不可达时无法补写终态，交给 TTL 兜底清除。
        }
    }

    /// <summary>
    /// 写终态 Stopped（幂等）。
    /// </summary>
    /// <remarks>
    /// Writes the terminal Stopped state (idempotent; the first writer wins).
    /// </remarks>
    /// <returns>异步任务 / Async task</returns>
    private Task WriteStoppedAsync()
    {
        return UpsertHeartbeatAsync(InstanceStatus.Stopped, CancellationToken.None);
    }

    /// <summary>
    /// 全量 upsert 本进程心跳文档。
    /// </summary>
    /// <remarks>
    /// Upserts the full heartbeat document (every field, always the latest state).
    /// </remarks>
    /// <param name="status">本次写入状态 / The status to write</param>
    /// <param name="cancellationToken">取消令牌 / The cancellation token</param>
    /// <returns>异步任务 / Async task</returns>
    private Task UpsertHeartbeatAsync(InstanceStatus status, CancellationToken cancellationToken)
    {
        if (Interlocked.CompareExchange(ref _stoppedWritten, 1, 0) != 0 && status != InstanceStatus.Stopped)
        {
            return Task.CompletedTask;
        }

        var document = new ServerHeartbeatDocument(
            _selfDescriptor.InstanceId,
            _selfDescriptor.Role,
            _selfDescriptor.AdvertiseEndpoint,
            status.ToString(),
            0, // 负载自报：固定 0，接真实指标源属后续 change（ponytail：升级路径 = 注入负载采样回调）。
            _selfDescriptor.AddressKind.ToString(),
            _selfDescriptor.Incarnation,
            DateTime.UtcNow);
        return _collection.ReplaceOneAsync(
            Builders<ServerHeartbeatDocument>.Filter.Eq(candidate => candidate.InstanceId, _selfDescriptor.InstanceId),
            document,
            new ReplaceOptions { IsUpsert = true },
            cancellationToken);
    }

    /// <summary>
    /// 探测出口地址（IPv4 优先，失败回退 IPv6/本机名）。
    /// </summary>
    /// <remarks>
    /// Detects the egress address: a UDP socket connect (no packet sent) to a public
    /// address yields the IPv4 egress; on failure the host's resolved addresses are
    /// scanned (IPv4 first, then IPv6); the machine name is the last resort, logged
    /// as a warning per the D15 risks mitigation.
    /// </remarks>
    /// <returns>出口主机与形态 / The egress host and its address kind</returns>
    private static (string Host, EndpointAddressKind AddressKind) DetectEgressAddress()
    {
        try
        {
            using (var probeSocket = new Socket(AddressFamily.InterNetwork, SocketType.Dgram, ProtocolType.Udp))
            {
                probeSocket.Connect("8.8.8.8", 65530);
                if (probeSocket.LocalEndPoint is IPEndPoint ipv4EndPoint && !string.IsNullOrEmpty(ipv4EndPoint.Address.ToString()))
                {
                    return (ipv4EndPoint.Address.ToString(), EndpointAddressKind.IPv4);
                }
            }
        }
        catch (Exception)
        {
            // 无外网路由（隔离网络/CI）：走主机地址表回退。
        }

        try
        {
            var hostAddresses = Dns.GetHostAddresses(Dns.GetHostName());
            foreach (var address in hostAddresses)
            {
                if (address.AddressFamily == AddressFamily.InterNetwork)
                {
                    return (address.ToString(), EndpointAddressKind.IPv4);
                }
            }

            foreach (var address in hostAddresses)
            {
                if (address.AddressFamily == AddressFamily.InterNetworkV6)
                {
                    return (address.ToString(), EndpointAddressKind.IPv6);
                }
            }
        }
        catch (Exception)
        {
            // 主机名解析失败：最后回退本机名。
        }

        var machineName = Dns.GetHostName();
        LogHelper.Warning("[MongoEndpointRegistry] egress address detection failed; falling back to the machine name {machineName} as the advertise host. Set {environmentVariable} explicitly when cross-process routing is required.", machineName, AdvertiseHostEnvironmentVariable);
        return (machineName, EndpointAddressKind.DnsName);
    }
}
