
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using GameFrameX.Core.Config;

namespace GameFrameX.Config.Tables
{
    public partial class TbAchievementConfig : BaseDataTable<Tables.AchievementConfig>
    {
        private readonly System.Func<System.Threading.Tasks.Task<ByteBuf>> _loadFunc;

        public TbAchievementConfig(System.Func<System.Threading.Tasks.Task<ByteBuf>> loadFunc)
        {
            _loadFunc = loadFunc;
        }

        public override async System.Threading.Tasks.Task LoadAsync()
        {
            ByteBuf _buf = await _loadFunc();
            StringDataMaps.Clear();
            LongDataMaps.Clear();
            DataList.Clear();
            for(int n = _buf.ReadSize() ; n > 0 ; --n)
            {
                Tables.AchievementConfig _v;
                _v = global::GameFrameX.Config.Tables.AchievementConfig.DeserializeAchievementConfig(_buf);
                DataList.Add(_v);
                LongDataMaps.Add(_v.Id, _v);
                StringDataMaps.Add(_v.Id.ToString(), _v);
            }
            PostInit();
        }


        public void ResolveRef(TablesComponent tables)
        {
            foreach(var value in DataList)
            {
                value.ResolveRef(tables);
            }
            PostResolveRef();
        }

        public void TranslateText(System.Func<string, string, string> translator)
        {
            foreach(var v in DataList)
            {
                v.TranslateText(translator);
            }
        }


        partial void PostInit();
        partial void PostResolveRef();
    }
}
